### ISSUE TITLE
Change highlight color

### ISSUE THREAD

**Issue by Shulin** [shardulm94/vscode-trailingspaces#12]
It'd be great to be able to change the highlight color!

Thanks for porting this plugin over!~

**Comment by aminimalanimal** [comment]
Would also be great to be able to prevent highlighting at all (useful if you just let it trim them on save).

**Comment by shardulm94** [comment]
Thanks @yustnip for your PR. I included your changes in 7ead91faf1848b095753114efea89675efc055d6.
@Shulin @aminimalanimal  Can you try to see if the new beta release solves this?
https://github.com/shardulm94/vscode-trailingspaces/releases/tag/v0.3.0-rc3
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by shardulm94** [comment]
Released in v0.3.0 available in marketplace
