### ISSUE TITLE
Option to turn off highlighting errors for spaces before a line

### ISSUE THREAD

**Issue by jayden2** [shardulm94/vscode-trailingspaces#13]
For example, between brackets properties can be put on a new line:

![screenshot from 2017-09-05 15-13-57](https://user-images.githubusercontent.com/11433659/30049384-071e2ec0-924d-11e7-88c3-bea1e7354017.png)

when using spaces this can mean an odd number of spaces to line up with a bracket, right now this happens because the spaces before default and editable properties would be red.

Suggestion would be to add a setting to ignore spaces starting spaces on a line.

**Comment by shardulm94** [comment]
Sorry for responding so late, but I cannot reproduce this.
![image](https://user-images.githubusercontent.com/6961317/55189421-20762c00-515b-11e9-907c-29c3b90fc993.png)

Can you share the settings for the extension? I suspect the regexp setting may be modified.

**Comment by shardulm94** [comment]
Please re-open if you still face this issue after updating to v0.3.0 which is now available in the marketplace.
