### ISSUE TITLE
FEATURE: Trim all lines except current cursor line

### ISSUE THREAD

**Issue by SanderBeekhuis** [shardulm94/vscode-trailingspaces#14]
Hi, thanks for this great extension.

I use a workflow where i let vs code autosave often and let your extension trim on save. This works like a charm, except when I start a new line and then pause for a bit.

Is it possible to make a setting that trims all lines except for the one with the cursor on it. Similar to the setting for highlighting you already have  `trailing-spaces.highlightCurrentLine`.

Let me know if I can help.

**Comment by SanderBeekhuis** [comment]
Actually the core `trimTrailingWhitespace`. Seems to do the trick. So I set trailing-whitespaces to highlighting only mode.

**Comment by Luifr** [comment]
@SanderBeekhuis the problem with `files.trimTrailingWhitespace` is that it ignores non modified lines, like this option: `"trailing-spaces.deleteModifiedLinesOnly": true`

I suggest opening this as issue/feature request

**Comment by SanderBeekhuis** [comment]
@Luifr I like the way it works. I don't mind it deleting whitespace in the whole file. Feel free to make an issue yourself if you don´t like the way it works. :)

**Comment by patbl** [comment]
I'm confused. How do you trim trailing whitespace on all lines except the current one?

Enabling `files.trimTrailingWhitespace` trims trailing whitespace on all lines including the current one.

**Comment by bryango** [comment]
I also find that `files.trimTrailingWhitespace` is not working for me; the current line seems to be trimmed as well!

**Comment by Temulgeh** [comment]
This is now a bit old, but same thing here. It's not a big issue but it's still kind of annoying.
