### ISSUE TITLE
Bug: Command not found

### ISSUE THREAD

**Issue by lumodon** [shardulm94/vscode-trailingspaces#20]
## Bug
Extension no longer works. Whitespace not being highlighted. Upon attempting `Command+Shift+P` and trying `> Trailing Spaces: Highlight` I receive the following error:
```
command 'trailing-spaces.highlightTrailingSpaces' not found
```

Mac OsX - Visual Studio Code Version 1.26.1 (1.26.1)
Trailing Spaces 0.2.11

<img width="1280" alt="trailingspaceserror" src="https://user-images.githubusercontent.com/10302608/45249256-542e5900-b2d2-11e8-92be-5e3e924b9f49.png">

**Comment by insert0003** [comment]
I meet same issue on Ubuntu 16.04,  vscode 1.27.2, Trailing Spaces 0.2.11

**Comment by shardulm94** [comment]
@lumodon Sorry for the late response. I am not able to reproduce the issue on my end. Is this still an issue? Can you try to see if the new beta release has the same issue? 
https://github.com/shardulm94/vscode-trailingspaces/releases/tag/v0.3.0-rc1
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by shardulm94** [comment]
c
