### ISSUE TITLE
Ignore text in the output window

### ISSUE THREAD

**Issue by Peter92** [shardulm94/vscode-trailingspaces#25]
I've noticed that the output window is also affected by the extension. It's not something that can be controlled by normal users, so it'd be nice if it was disabled (if possible), but maybe with an option to re-enable if you do actually require it.

Here's an example of what I mean:

![image](https://user-images.githubusercontent.com/10235666/52407800-2475be00-2ac9-11e9-88d8-39a006704a2b.png)

**Comment by shardulm94** [comment]
@Peter92 It is not intended for the extension to highlight trailing spaces in the output window. Based on the VSCode APIs being used, the output windows would never be accessed. Can you provide some steps to reproduce the issue?

**Comment by shardulm94** [comment]
Okay it seems like the VSCode API considers output windows as text editors. Microsoft/vscode#36579
I will try to see if there is a way I can differentiate between an editor and an output window using the API.

**Comment by shardulm94** [comment]
@Peter92 Added a new option `trailing-spaces.schemeIgnore` to support this. You can ignore the `output` scheme to disable highlighting in output windows. This is planned for release in [`v0.3.0`](../milestone/1). Can you try to see if the new beta release resolves this?
https://github.com/shardulm94/vscode-trailingspaces/releases/tag/v0.3.0-rc4
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by Peter92** [comment]
Ah nice one, just tried it and it works fine :)

A suggestion for before you fully release it, keep the `schemeIgnore` list for advanced users, but open up the main schemes as checkboxes, perhaps with all but the main window disabled by default.

**Comment by shardulm94** [comment]
I don't think opening up schemes as checkboxes is scalable. I think the way to disable schemes is easy enough for non-advanced users to understand. I made one change, now it will ignore `output` schemes by default since it was not intended to be highlighted in the first place.
