### ISSUE TITLE
feature request: add `no highlight` option

### ISSUE THREAD

**Issue by cheng10** [shardulm94/vscode-trailingspaces#32]
Hi, I found your tool very useful. I mainly use it to trim trailing whitespaces in modified lines.

However, I do not need the highlight function which is constantly enforced in VS code. The highlight can be distracting but I do not really care about it since I enabled the `trim on save` option.  I couldn't find a place to turn the highlight off while keeping the `trim on save` function.

It would be very helpful to add a `turn off highlight` option in the settings. Thanks!

**Comment by Gruntfuggly** [comment]
You know vscode has a built in trim on save?
`"files.trimTrailingWhitespace": true`
unless you're also using the trim modified lines only feature of course...

**Comment by cheng10** [comment]
Yes, I specifically need trim on modified lines, as I do not want to modify other people's lines because trivial issues like trailing white spaces.

**Comment by Gruntfuggly** [comment]
Fair enough - I have the same problem (legacy codebases!).

You can specify the highlight colour (and border) with an alpha value, so setting it to 0.0 will make them invisible.

**Comment by shardulm94** [comment]
As @Gruntfuggly suggested, setting the alpha value (last parameter) of the color values to `0` should make them invisible. 
E.g. `rgba(255,255,255,0)`
