### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yaboojp** [shardulm94/vscode-trailingspaces#33]
- Issue Type: `Performance`
- Extension Name: `trailing-spaces`
- Extension Version: `0.3.1`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.35.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/hisashi/shardulm94.trailing-spaces-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by shardulm94** [comment]
Can you attach the CPU profiling file as mentioned in the description?

**Comment by shardulm94** [comment]
Closing since the report does not include the CPU profile file.
