### ISSUE TITLE
Bug: TrimOnSave causes cursor movement when VS Code's Auto-Save option is enabled

### ISSUE THREAD

**Issue by Asaf-S** [shardulm94/vscode-trailingspaces#34]
Hey man, great extension! It makes it more fun to code...
I'm having a small problem with it when VS Code's Auto-Save option is enabled.

Let's say I've defined a new function (and placed the cursor as illustrated below):
```javascript
function NewFunc() {
    [cursor is now here, i.e. indented]
}
```

If I take a moment to think, VS Code saves the file as expected, and therefore the trailing whitespace is trimmed (expected) - however the whitespace before of the cursor is also trimmed.
```javascript
function NewFunc() {
[cursor is now here, no indentation]
}
```

When I continue typing, it starts from the beginning of the row, instead of being indented:
```javascript
function NewFunc() {
console.log("I've just typed this row");
}
```

And I later need to manually fix the indentation:
```javascript
function NewFunc() {
    console.log("The row was manually indented");
}
```

I guess the expected behavior would be to analyze the cursor position, and avoid trimming the whitespace before it (the whitespace after it - is ok to trim I guess).

I there anything you can do about it? This is slowing me down, and I might be forced to stop using your great extension.

**Comment by mitchellsimoens** [comment]
I am running up against this same issue and thought of the same solution (do not trim where the cursor is).

**Comment by Asaf-S** [comment]
Since then, I've found that there's such an option in VSCode without extensions.
It's called: editor.trimAutoWhitespace
