### ISSUE TITLE
Sticky highlighted trailing spaces after font zooming

### ISSUE THREAD

**Issue by pelco** [shardulm94/vscode-trailingspaces#40]
If we have some text with highlighted trailing spaces like:
![image](https://user-images.githubusercontent.com/16528048/83027500-19310380-a028-11ea-8b63-1a3a56155022.png)

If we zoom the font using `ctrl +` or `ctrl -`
![image](https://user-images.githubusercontent.com/16528048/83027532-1fbf7b00-a028-11ea-8171-bc0867ee574f.png)

Those highlighted trailing spaces won't disappear and will highlight all text that comes afterward.
![image](https://user-images.githubusercontent.com/16528048/83027719-5c8b7200-a028-11ea-9211-d734a4049595.png)

**Comment by shardulm94** [comment]
Able to reproduce. Thanks for reporting! The only workaround I can think of for now is to close and reopen the file after zoom level change or reload the window.

**Comment by pelco** [comment]
Yes, but it doesn't seem to be a good fix!

**Comment by abrahammurciano** [comment]
I know this is not very helpful, but I find that this happens sometimes to me without necessarily changing the zoom. it's rare enough that it's not annoying to reopen the file, and I've not been able to determine what triggers it, but I thought you should know that it does happen other times too.

**Comment by shardulm94** [comment]
Thanks @abrahammurciano. This was not related to zoom level specifically, but could occur after any setting in VSCode is changed (including zoom level).
