### ISSUE TITLE
Ignore by extension or Ignore .*mdx

### ISSUE THREAD

**Issue by albertcito** [shardulm94/vscode-trailingspaces#41]
I'm working with [*.mdx](https://mdxjs.com/) files that is   _Markdown_  file. I added the [Ignore Syntax](https://github.com/shardulm94/vscode-trailingspaces#ignore-syntax) for this kind of files and it works with *.md files but not with *.mdx files.  Is there a way to ignore files by extension?. Thanks.

**Comment by shardulm94** [comment]
@albertcito Trailing spaces uses VSCode's language identifiers for this feature. In this case, seems like VSCode does not associate .mdx files to Markdown by default. You can change the language association for mdx files to Markdown in your VSCode settings and that should fix it.

![image](https://user-images.githubusercontent.com/6961317/91213530-9707b800-e6c6-11ea-9aa2-231b16e77c4b.png)

**Comment by albertcito** [comment]
That works perfect. Thank you a lot!
