### ISSUE TITLE
Unable to transition from VSCode market to this repository

### ISSUE THREAD

**Issue by sena-v** [shardulm94/vscode-trailingspaces#57]
Because the link referring to the repository in `package.json` has a "git+" prefix, it is not possible to transition directly to the repository from the VSCode market.

```bash
  "repository": {
    "type": "git",
    "url": "git+https://github.com/shardulm94/vscode-trailingspaces.git"
  },
```

Is this code intended?　Please correct if possible.

**Comment by shardulm94** [comment]
Fixed in the latest update
