### ISSUE TITLE
Highlight error

### ISSUE THREAD

**Issue by ws-perelyaynen** [shardulm94/vscode-trailingspaces#6]
`No handler found for the command: 'trailing-spaces.highlightTrailingSpaces'. An extension might be missing an activation event.`
have no idea how to fix it

**Comment by shardulm94** [comment]
Hi,

May know which version of the extension you are using and also the version of vscode?

**Comment by ws-perelyaynen** [comment]
Sorry, issue should be closed.
Changed  theme to  'Material Theme Kit ', all works. Thank you for fast reply =)
VScode v.1.0.0
Trailing space 0.2.8

**Comment by shardulm94** [comment]
Well, strange!
Should work with all themes. Can you let me know for which theme it was failing?
Just want to make sure that there's no conflict issue before closing.
Thanks.

**Comment by ws-perelyaynen** [comment]
I started from scratch, so it was clean VS with default theme( i didn't remember, which of default themes was, but i didn't change it before)

**Comment by shardulm94** [comment]
No issues, I will try to reproduce it.

**Comment by shardulm94** [comment]
Fixed in https://github.com/shardulm94/vscode-trailingspaces/commit/f9e048451eba2892cf8370c5adc08add7bd1ba32
