### ISSUE TITLE
on split window view trailing-space extension throws exception

### ISSUE THREAD

**Issue by NikosEfthias** [shardulm94/vscode-trailingspaces#7]
![](https://camo.githubusercontent.com/045dbfd65429ae578bd814dbef74a9e1a09234f8/687474703a2f2f692e696d6775722e636f6d2f36333556336f7a2e706e67)

**Comment by shardulm94** [comment]
On the git diff view? or just any split editor?

**Comment by NikosEfthias** [comment]
i just splitted the editor in order to edit 2 files simultaneously and it crashed

**Comment by shardulm94** [comment]
Thanks! will investigate this on linux tonight. Not able to reproduce on windows. Thanks for this! You have been a great help!

**Comment by NikosEfthias** [comment]
:) i thank you for this extension

**Comment by shardulm94** [comment]
Not able to reproduce. Certainly looks like some issue with the extension. Will keep this open for now and investigate further.

**Comment by NikosEfthias** [comment]
![](http://i.imgur.com/eqEmC6O.png) again this error started and this time completely i cannot use extension even after  removing and installing back

**Comment by shardulm94** [comment]
@NikosEfthias The extension is not able to read its configuration. Pretty sure this issue is directly related to [this issue in vscode](https://github.com/Microsoft/vscode/issues/5649). The May release of vscode should fix it.

**Comment by shardulm94** [comment]
Also, I was successfully able to reproduce it in the insiders build. Will keep an eye on this when the new version releases.

**Comment by NikosEfthias** [comment]
so at the moment we are waiting for a new release :)

**Comment by shardulm94** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/957653954a359386045cabe6684b280414d6083d https://github.com/Microsoft/vscode/issues/5649
Updating VSCode to the latest version should resolve it.
