### ISSUE TITLE
Markdown wrap spaces issue

### ISSUE THREAD

**Issue by Charley2012** [shardulm94/vscode-trailingspaces#75]
Hello!

Please look at the picture bellow:
<img width="357" alt="捕获" src="https://github.com/shardulm94/vscode-trailingspaces/assets/130669275/e17b3e85-29e8-4215-abba-ab987b07de8e">

As you can see, the spaces to wrap the line in Markdown has been recognized as trailing spaces. But they should not.

Thanks!

**Comment by parmentelat** [comment]
see also #56
